import { useEffect, useState } from 'react';

// Uses the SW generated by vite-plugin-pwa (registerType: autoUpdate)
// and exposes a simple 'update available' flag.

export function useServiceWorkerUpdate() {
  const [hasUpdate, setHasUpdate] = useState(false);

  useEffect(() => {
    if (!('serviceWorker' in navigator)) return;

    let refreshing = false;

    navigator.serviceWorker.addEventListener('controllerchange', () => {
      if (refreshing) return;
      refreshing = true;
      window.location.reload();
    });

    // vite-plugin-pwa injects 'virtual:pwa-register' normally, but for a minimal setup
    // we fallback to a direct registration if a SW exists at /sw.js.
    void navigator.serviceWorker
      .register('/sw.js')
      .then((reg) => {
        reg.addEventListener('updatefound', () => {
          const newWorker = reg.installing;
          if (!newWorker) return;
          newWorker.addEventListener('statechange', () => {
            if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
              setHasUpdate(true);
            }
          });
        });
      })
      .catch(() => {
        // ignore
      });
  }, []);

  function applyUpdateNow() {
    // simplest: reload to let new SW take over
    window.location.reload();
  }

  return { hasUpdate, applyUpdateNow };
}
